Repository AY2425S2-CS2103T-T09-1/tp, pull requests merged in 2025-04, with the labels that each got.

#142 Use natural language for date parsing
  build.gradle
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/DateParserUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
Labels: type.Enhancement, priority.High

#165 Update DG description related to add
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#163 Improve on GUI
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#153 150 update uml related to find and sort function
  docs/diagrams/FindAddressSequenceDiagram.puml
  docs/diagrams/FindEmailSequenceDiagram.puml
  docs/diagrams/FindNameSequenceDiagram.puml
  docs/diagrams/FindPhoneSequenceDiagram.puml
  docs/diagrams/FindRelationshipSequenceDiagram.puml
  docs/diagrams/FindSocialSequenceDiagram.puml
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task

#166 Add redo command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RedoListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/RedoListCommandParser.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
Labels: type.Task

#179 Add unit test for Tran Khoi Nguyen's code
  src/main/java/seedu/address/logic/commands/FindRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RedoListCommand.java
  src/main/java/seedu/address/logic/parser/RedoCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/commandhistory/CommandHistory.java
  src/main/java/seedu/address/model/list/SortedFilteredList.java
  src/test/java/seedu/address/logic/commands/FindAddressCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEmailCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/FindSocialCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoListCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/FindAddressCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindEmailCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindPhoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindSocialCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RedoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RedoListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/commandhistory/CommandHistoryTest.java
  src/test/java/seedu/address/model/predicate/NameContainsKeywordsAsSubstringPredicateTest.java
  src/test/java/seedu/address/model/predicate/RelationshipContainsKeywordsAsSubstringPredicateTest.java
  src/test/java/seedu/address/model/predicate/SocialContainsKeywordsAsSubstringPredicateTest.java
  src/test/java/seedu/address/model/predicate/TagContainsKeywordsAsSubstringPredicateTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersonsTestSet2.java
Labels: type.Task

#190 Update user guide and developer guide for search sort redo redo list commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/predicate/TagContainsKeywordsAsSubstringPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/model/predicate/TagContainsKeywordsAsSubstringPredicateTest.java
Labels: type.Task

#187 Fix content not filling window
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, alpha-bug, type.FunctionalityBug

#191 Update UML for DateParserUtil
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: type.Task

#194 Update UML class diagrams for Relationships
  .gitignore
  docs/diagrams/JsonAdaptedRelationshipClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RelationshipClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UniqueRelationshipListClassDiagram.puml
  docs/diagrams/style.puml
Labels: type.Task

#186 Add puml diagram for event commands
  docs/diagrams/AddContactToEvent.puml
  docs/diagrams/AddEventCommandDiagram.puml
  docs/diagrams/AddTagToEventDiagram.puml
  docs/diagrams/DeleteContactFromEvent.puml
  docs/diagrams/DeleteEventCommandDiagram.puml
  docs/diagrams/DeleteTagFromEvent.puml
  docs/diagrams/EventCommandDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UpdateEventDescriptionCommandDiagram.puml
  docs/images/AddContactToEvent.png
  docs/images/AddEventCommandDiagram.png
  docs/images/AddTagToEventDiagram.png
  docs/images/DeleteContactFromEvent.png
  docs/images/DeleteEventCommandDiagram.png
  docs/images/DeleteTagFromEvent.png
  docs/images/ModelClassDiagram.png
  docs/images/UpdateEventDescriptionCommandDiagram.png
Labels: type.Enhancement

#197 Update location event
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UpdateEventDate.puml
  docs/diagrams/UpdateEventLocation.puml
  docs/images/UpdateEventDate.png
  docs/images/UpdateEventLocation.png
  src/main/java/seedu/address/logic/commands/UpdateEventDateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateEventLocationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventDateCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventLocationCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
Labels: type.Enhancement

#198 170 update ug
  docs/UserGuide.md
Labels: type.DocumentationBug

#199 Improve code quality for Relationships
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/predicate/RelationshipContainsKeywordsAsSubstringPredicate.java
  src/main/java/seedu/address/model/relationship/Relationship.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/main/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipException.java
  src/main/java/seedu/address/model/relationship/exceptions/RelationshipNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/model/relationship/RelationshipTest.java
  src/test/java/seedu/address/testutil/RelationshipBuilder.java
Labels: type.Task

#200 Add UML sequence diagrams for Relationship commands
  docs/diagrams/AddRelationshipSequenceDiagram.puml
  docs/diagrams/AddTagToRelationshipSequenceDiagram.puml
  docs/diagrams/DeleteRelationshipSequenceDiagram.puml
  docs/diagrams/DeleteTagFromRelationshipSequenceDiagram.puml
  docs/images/AddRelationshipSequenceDiagram.png
  docs/images/AddTagToRelationshipSequenceDiagram.png
  docs/images/DeleteRelationshipSequenceDiagram.png
  docs/images/DeleteTagFromRelationshipSequenceDiagram.png
Labels: type.Task

#203 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/EventCommandDiagram.puml
  docs/diagrams/FindAddressSequenceDiagram.puml
  docs/diagrams/RelationshipClassDiagram.puml
  docs/diagrams/UniqueRelationshipListClassDiagram.puml
  docs/images/AddContactToEvent.png
  docs/images/AddEventCommandDiagram.png
  docs/images/AddTagToEventDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteContactFromEvent.png
  docs/images/DeleteEventCommandDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteTagFromEvent.png
  docs/images/FindAddressSequenceDiagram.png
  docs/images/FindEmailSequenceDiagram.png
  docs/images/FindNameSequenceDiagram.png
  docs/images/FindPhoneSequenceDiagram.png
  docs/images/FindRelationshipSequenceDiagram.png
  docs/images/FindSocialSequenceDiagram.png
  docs/images/FindTagSequenceDiagram.png
  docs/images/JsonAdaptedRelationshipClassDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/RelationshipClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoState0-Initial_state.png
  docs/images/UndoRedoState1-After_command__delete_5_.png
  docs/images/UndoRedoState2-After_command__add_n_David_.png
  docs/images/UndoRedoState3-After_command__undo_.png
  docs/images/UndoRedoState4-After_command__list_.png
  docs/images/UndoRedoState5-After_command__clear_.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  docs/images/UniqueRelationshipListClassDiagram.png
  docs/images/UpdateEventDate.png
  docs/images/UpdateEventDescriptionCommandDiagram.png
  docs/images/UpdateEventLocation.png
Labels: type.Task, priority.High

#202 Add redoList sequence diagram and redo sequence diagram
  docs/diagrams/RedoListSequenceDiagram.puml
  docs/diagrams/RedoSequenceDiagram.puml
Labels: type.Task

#209 Fix DG table of contents
  docs/DeveloperGuide.md
Labels: alpha-bug

#214 Update command summary in UG
  docs/UserGuide.md
Labels: alpha-bug

#220 Add logo in GUI
  src/main/resources/images/INcontact_logo.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#221 Update README.md file
  README.md
  docs/images/Ui.png
Labels: type.Task

#226 Update user guide quick start
  docs/UserGuide.md
Labels: type.Task

#227 Add openInTerminal.png
  docs/images/openInTerminal.png
Labels: type.DocumentationBug

#224 Rename AddressBook to INcontact
  docs/DevOps.md
  docs/SettingUp.md
  docs/index.md
Labels: type.DocumentationBug

#300 Update UI design
  src/main/resources/view/MainWindow.fxml
Labels: severity.VeryLow

#302 Fix add error message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: severity.VeryLow

#304 Update add parser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: severity.High

#307 Add tests for add
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/person/Address.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Task

#309 Handle relationship GUI bugs
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High

#312 Modify relationship delete messages
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
Labels: type.Bug

#313 Fix event contact and duplicate command
  src/main/java/seedu/address/logic/commands/AddContactToEventCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/UpdateEventDateCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventDescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateEventLocationCommandParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
Labels: type.Bug

#318 Update relevant UG documentations
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addPerson.png
  docs/images/addRelationship.png
  docs/images/clear.png
  docs/images/deletePerson.png
  docs/images/editPerson.png
  docs/images/helpMessage.png
  docs/images/list.png
Labels: type.Task

#316 Save data during application shutdown
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug

#315 Update documentation for Relationships
  docs/UserGuide.md
Labels: type.Task

#320 Remove id in contact
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventCard.fxml
Labels: type.Bug

#321 Update relevant UG documentations
  docs/UserGuide.md
Labels: type.Task

#324 229 more relationship tests
  src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTagToRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTagToRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagFromRelationshipCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/relationship/RelationshipTest.java
  src/test/java/seedu/address/model/relationship/UniqueRelationshipListTest.java
  src/test/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipExceptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalRelationships.java
Labels: type.Task

#325 Update relevant UG documentations
  docs/UserGuide.md
  docs/images/addEvent.png
  docs/images/addEventContact.png
  docs/images/addEventTag.png
  docs/images/addRelationshipTag.png
  docs/images/deleteEvent.png
  docs/images/deleteEventContact.png
  docs/images/deleteEventTag.png
  docs/images/deleteRelationship.png
  docs/images/deleteRelationshipTag.png
  docs/images/findAddress.png
  docs/images/findEmail.png
  docs/images/findPhone.png
  docs/images/findSocial.png
  docs/images/updateEventDate_command.png
  docs/images/updateEventDesc.png
  docs/images/updateEventLoc.png
Labels: priority.High

#332 Remove duplicates in ModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.DocumentationBug

#331 Fix sequence diagrams
  docs/diagrams/AddContactToEvent.puml
  docs/diagrams/AddEventCommandDiagram.puml
  docs/diagrams/AddRelationshipSequenceDiagram.puml
  docs/diagrams/AddTagToEventDiagram.puml
  docs/diagrams/AddTagToRelationshipSequenceDiagram.puml
  docs/diagrams/DeleteContactFromEvent.puml
  docs/diagrams/DeleteEventCommandDiagram.puml
  docs/diagrams/DeleteRelationshipSequenceDiagram.puml
  docs/diagrams/DeleteTagFromEvent.puml
  docs/diagrams/DeleteTagFromRelationshipSequenceDiagram.puml
  docs/diagrams/FindAddressSequenceDiagram.puml
  docs/diagrams/FindEmailSequenceDiagram.puml
  docs/diagrams/FindNameSequenceDiagram.puml
  docs/diagrams/FindPhoneSequenceDiagram.puml
  docs/diagrams/FindRelationshipSequenceDiagram.puml
  docs/diagrams/FindSocialSequenceDiagram.puml
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UpdateEventDate.puml
  docs/diagrams/UpdateEventDescriptionCommandDiagram.puml
  docs/diagrams/UpdateEventLocation.puml
  docs/images/AddContactToEvent.png
  docs/images/AddEventCommandDiagram.png
  docs/images/AddRelationshipSequenceDiagram.png
  docs/images/AddTagToEventDiagram.png
  docs/images/AddTagToRelationshipSequenceDiagram.png
  docs/images/DeleteContactFromEvent.png
  docs/images/DeleteEventCommandDiagram.png
  docs/images/DeleteRelationshipSequenceDiagram.png
  docs/images/DeleteTagFromEvent.png
  docs/images/DeleteTagFromRelationshipSequenceDiagram.png
  docs/images/FindAddressSequenceDiagram.png
  docs/images/FindEmailSequenceDiagram.png
  docs/images/FindNameSequenceDiagram.png
  docs/images/FindPhoneSequenceDiagram.png
  docs/images/FindRelationshipSequenceDiagram.png
  docs/images/FindSocialSequenceDiagram.png
  docs/images/FindTagSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/UpdateEventDate.png
  docs/images/UpdateEventDescriptionCommandDiagram.png
  docs/images/UpdateEventLocation.png
Labels: type.DocumentationBug

#328 Fix duplicate event id
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/event/Event.java
Labels: type.Bug

#333 Add picture for ug, modify ug, dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findRel.png
  docs/images/findTag.png
  docs/images/redo.png
  docs/images/redoList.png
  docs/images/sortByPhoneByname.png
Labels: type.Task
