Repository AY2425S2-CS2103T-T09-1/tp, pull requests merged in 2025-03, with the labels that each got.

#10 Add Tran's Photo
  docs/images/trknguyen.png
Labels: type.Task

#8 Add picture for itsvari
  docs/images/itsvari.png
Labels: type.Task

#12 Add @keyansheng's photo
  docs/images/keyansheng.png
Labels: type.Task

#11 Add stickiem.png
  docs/images/stickiem.png
Labels: type.Task

#16 add-chau-photo
  docs/images/chau.png
Labels: type.Task

#22 Update the AboutUs page with Tran's Information
  docs/AboutUs.md
Labels: type.Task

#17 Update AboutUs.md with Thum Kei Kuan's information
  docs/AboutUs.md
Labels: type.Task

#26 Update chau infomation for AboutUs
  docs/AboutUs.md
  docs/images/chauuule.png
Labels: type.Task

#19 Add AboutUs details for Ashe
  docs/AboutUs.md
  docs/images/itsvari.png
Labels: type.Task

#30 Update readme
  README.md
  docs/images/Ui.png
Labels: type.Task

#32 Update status badge
  README.md
Labels: type.Task

#34 Update README.md
  README.md
Labels: type.Task

#38 Add support for adding socials for the "add" command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Social.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#39 Update DG with target user profile, value proposition, and user stories
  docs/DeveloperGuide.md
Labels: type.Task

#52 Add relationships to INcontact
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/relationship/Relationship.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/main/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipException.java
  src/main/java/seedu/address/model/relationship/exceptions/RelationshipNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/relationship/RelationshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/RelationshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#54 Fix Java CI workflow
  .github/workflows/gradle.yml
Labels: type.Bug, priority.Medium

#47 Update Jekyll site settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.High

#44 Update DG with use cases
  docs/DeveloperGuide.md
Labels: type.Task

#46 Update DG with glossary
  docs/DeveloperGuide.md
Labels: type.Task

#62 Fix checkstyle errors
  README.md
  docs/AboutUs.md
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/AddRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteRelationshipCommandParser.java
  src/main/java/seedu/address/model/relationship/Relationship.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/main/java/seedu/address/model/relationship/exceptions/DuplicateRelationshipException.java
  src/main/java/seedu/address/model/relationship/exceptions/RelationshipNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRelationship.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/parser/AddRelationshipCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteRelationshipCommandParserTest.java
  src/test/java/seedu/address/model/relationship/RelationshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRelationshipTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/RelationshipBuilder.java
Labels: type.Task, type.Bug

#65 Fix error with event commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
Labels: type.Task, type.Bug

#70 Update checkstyle rules
  config/checkstyle/checkstyle.xml
Labels: type.Task, priority.Low

#73 Allow for adding social to be optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Social.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Enhancement

#75 Show UserID in the UI
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/relationship/Relationship.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRelationshipCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRelationshipCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, priority.High, severity.High

#78 Fix checkstyle and compile error
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Event.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Task, type.Bug

#81 Update documentation
  docs/UserGuide.md
  docs/index.md
Labels: type.Task

#88 Update window title to INcontact
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#86 Add event GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/resources/view/EventCard.fxml
  src/main/resources/view/EventList.css
  src/main/resources/view/EventListPanel.fxml
Labels: type.Task

#85 Fix commands in UserGuide.md
  docs/UserGuide.md
Labels: type.Task

#120 94 improve fields
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Enhancement

#117 Add contacts to events
  src/main/java/seedu/address/logic/commands/AddContactToEventCommand.java
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactFromEventCommand.java
  src/main/java/seedu/address/logic/parser/AddContactToEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteContactFromEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
Labels: type.Enhancement, priority.High

#121 Allow adding and removing tags from existing relationships
  src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommand.java
  src/main/java/seedu/address/logic/parser/AddTagToRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagFromRelationshipCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/relationship/Relationship.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Enhancement, priority.High

#125 124 refresh gui on relationship add
  src/main/java/seedu/address/logic/commands/AddRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRelationshipCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Bug, priority.High, severity.Medium

#128 Add extra tests
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/relationship/UniqueRelationshipList.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Bug

#130 Add extra help text to relationship tag command strings
  src/main/java/seedu/address/logic/commands/AddTagToRelationshipCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagFromRelationshipCommand.java
Labels: type.Bug

#132 Fix message error format
  src/main/java/seedu/address/logic/commands/AddTagToEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactFromEventCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagFromEventCommand.java
Labels: type.Bug

#135 Build for release
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/FindNameCommandParserTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Task

#138 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#141 139 update uml sort sequence
  docs/diagrams/SortSequenceDiagram.puml
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindRelationshipCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/list/SortedFilteredList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/predicate/RelationshipContainsKeywordsAsSubstringPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task
